#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [[ -s "/usr/local/etc/grc.zsh" ]]; 
then
  source "/usr/local/etc/grc.zsh"
elif [[ -s "/etc/grc.zsh" ]];
then
  source "/etc/grc.zsh"
fi


# Customize to your needs...

DEFAULT_USER='nwykes'
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_VCS_GIT_ICON=' '
POWERLEVEL9K_DIR_HOME_FOREGROUND='07'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='07'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='07'
POWERLEVEL9K_DIR_ETC_FOREGROUND='07'
POWERLEVEL9K_DIR_HOME_BACKGROUND='grey23'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='grey23'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='grey23'
POWERLEVEL9K_DIR_ETC_BACKGROUND='grey23'
POWERLEVEL9K_DIR_PATH_HIGHLIGHT_BOLD=true
POWERLEVEL9K_DIR_PATH_HIGHLIGHT_FOREGROUND='07'
POWERLEVEL9K_OS_ICON_BACKGROUND='04'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator os_icon context dir dir_writable vcs)